version: '3'
services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    image: playwright_python
    volumes:
      - ./src:/code
    working_dir: /code
    command: "pytest --html=report.html --browser chromium --browser firefox"